[project]
name = "thesis-code"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.9.2",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tensorflow>=2.19.0",
    "tree-sitter>=0.24.0",
    "tree-sitter-language-pack>=0.7.2",
]
